name: CI App
on: push

jobs:
  build:
    name: Node build
    runs-on: ubuntu-latest
    env:
      DB_DIALECT: sqlite
    steps:
      - uses: actions/checkout@v1
      - uses: hallee/eslint-action@1.0.1
      - run: yarn
      - run: yarn test
