name: CI App
on: push

jobs:
  build:
    name: Node build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/node/
      - run: yarn
      - run: yarn test
